### ISSUE TITLE
Skill ref reverse links

### ISSUE THREAD

**Issue by reinderien** [reinderien/arcanum-libri#1]
> One thing I think would be highly useful would be to be able to look up a Skill and see all the ways to increase its max.  I think that information is mostly out there, but it's not indexed in a way that puts it in one place.

- Elestan, [Arcanum users-code Discord](https://discord.com/channels/622495527485046805/624055987912835083/978731005013819442)

**Comment by reinderien** [comment]
As of fb7900 this is done (at least for the data we have so far: tiers, classes and skills).

**Comment by Lamphobic** [comment]
fb79000

(Fixing the link to the commit.)
